## **Antarctic Plateau Salt Relative Humidity and Temperature Dataset (APSRHT) - Cleaning**

Dataset: Davila, A; Parro, V. Antarctic Plateau-Salt Relative Humidity and Temperature. Astrobiology Habitable Environment Database. Retrieved Date: Jun 23, 2026. https://doi.org/10.48667/sy0j-yc84

"First column is the measurement number. Second column is the date/time of each measurement. Third column is the temperature in degrees Celssius. Fourth column is the RH as measured by the sensor. Fifth column is the RH with respect to ice"

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('Antarctic_Plateau_Salt data.csv', encoding='latin1')
data.columns = data.iloc[0]
data = data[1:].reset_index(drop=True)
data

0         #      Date Time   T (¼C)  RH (%) RH (ice) (%)
0     11549  12/19/18 0:00  -20.167  53.306        64.41
1     11550  12/19/18 0:15  -20.073  53.239        64.29
2     11551  12/19/18 0:30  -19.839  53.167        64.06
3     11552  12/19/18 0:45    -19.7  53.189        63.99
4     11553  12/19/18 1:00  -19.469  53.389        64.04
...     ...            ...      ...     ...          ...
4411  15960   2/2/19 22:45  -34.677  54.135        74.68
4412  15961   2/2/19 23:00  -34.593  54.226        74.71
4413  15962   2/2/19 23:15  -34.427  54.357        74.73
4414  15963   2/2/19 23:30  -34.262  54.487        74.76
4415  15964   2/2/19 23:45  -34.098  54.617        74.78

[4416 rows x 5 columns]

In [3]:
### rename columns
data = data.rename(columns={'#': 'measurement_number', 'Date Time': 'date_time', 'T (¼C)': 'temp_C', 'RH (%)': 'relative_humidity', 'RH (ice) (%)': 'relative_humidity_corrected'})
data.head()

,measurement_number,date_time,temp_C,relative_humidity,relative_humidity_corrected
0,11549,12/19/18 0:00,-20.167,53.306,64.41
1,11550,12/19/18 0:15,-20.073,53.239,64.29
2,11551,12/19/18 0:30,-19.839,53.167,64.06
3,11552,12/19/18 0:45,-19.7,53.189,63.99
4,11553,12/19/18 1:00,-19.469,53.389,64.04

In [4]:
### convert the column to datetime
data['date_time'] = pd.to_datetime(data['date_time'], format='%m/%d/%y %H:%M')
data.head()

,measurement_number,date_time,temp_C,relative_humidity,relative_humidity_corrected
0,11549,2018-12-19 00:00:00,-20.167,53.306,64.41
1,11550,2018-12-19 00:15:00,-20.073,53.239,64.29
2,11551,2018-12-19 00:30:00,-19.839,53.167,64.06
3,11552,2018-12-19 00:45:00,-19.7,53.189,63.99
4,11553,2018-12-19 01:00:00,-19.469,53.389,64.04

In [5]:
### set datetime as the dataframe index
data.set_index('date_time', inplace=True)
data.head()

,measurement_number,temp_C,relative_humidity,relative_humidity_corrected
date_time,,,,
2018-12-19 00:00:00,11549,-20.167,53.306,64.41
2018-12-19 00:15:00,11550,-20.073,53.239,64.29
2018-12-19 00:30:00,11551,-19.839,53.167,64.06
2018-12-19 00:45:00,11552,-19.7,53.189,63.99
2018-12-19 01:00:00,11553,-19.469,53.389,64.04

In [6]:
## create a complete 15-minute grid from start to end date
full_time_index = pd.date_range(start=data.index.min(), end=data.index.max(), freq='15min')
full_time_index

DatetimeIndex(['2018-12-19 00:00:00', '2018-12-19 00:15:00',
               '2018-12-19 00:30:00', '2018-12-19 00:45:00',
               '2018-12-19 01:00:00', '2018-12-19 01:15:00',
               '2018-12-19 01:30:00', '2018-12-19 01:45:00',
               '2018-12-19 02:00:00', '2018-12-19 02:15:00',
               ...
               '2019-02-02 21:30:00', '2019-02-02 21:45:00',
               '2019-02-02 22:00:00', '2019-02-02 22:15:00',
               '2019-02-02 22:30:00', '2019-02-02 22:45:00',
               '2019-02-02 23:00:00', '2019-02-02 23:15:00',
               '2019-02-02 23:30:00', '2019-02-02 23:45:00'],
              dtype='datetime64[ns]', length=4416, freq='15min')

In [7]:
### re-index dataframe to find gaps
data = data.reindex(full_time_index)
data.head()

,measurement_number,temp_C,relative_humidity,relative_humidity_corrected
2018-12-19 00:00:00,11549,-20.167,53.306,64.41
2018-12-19 00:15:00,11550,-20.073,53.239,64.29
2018-12-19 00:30:00,11551,-19.839,53.167,64.06
2018-12-19 00:45:00,11552,-19.7,53.189,63.99
2018-12-19 01:00:00,11553,-19.469,53.389,64.04

In [8]:
### date_time/index broken down into useful data columns
### 0=Monday, 1=Tuesday, 2=Wednesday, 3=Thursday, 4=Friday, 5=Saturday, 6=Sunday
data['year'] = data.index.year
data['month'] = data.index.month
data['day'] = data.index.day
data['hour'] = data.index.hour
data['day_of_week'] = data.index.dayofweek
data.head()

,measurement_number,temp_C,relative_humidity,relative_humidity_corrected,year,month,day,hour,day_of_week
2018-12-19 00:00:00,11549,-20.167,53.306,64.41,2018,12,19,0,2
2018-12-19 00:15:00,11550,-20.073,53.239,64.29,2018,12,19,0,2
2018-12-19 00:30:00,11551,-19.839,53.167,64.06,2018,12,19,0,2
2018-12-19 00:45:00,11552,-19.7,53.189,63.99,2018,12,19,0,2
2018-12-19 01:00:00,11553,-19.469,53.389,64.04,2018,12,19,1,2

In [9]:
### write to .csv
data.to_csv('apsrht_cleaned.csv', index=False, encoding='utf-8')